
OrdererOrgs:
  - Name: Orderer
    Domain: default.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
PeerOrgs:
  - Name: default
    Domain: default.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: default
        CommonName: default
    Users:
      Count: 1


      

      