# The default template
# If edit this file, should edit gen-crypto.sh either

OrdererOrgs:
  - Name: Orderer
    Domain: bolt.com
    EnableNodeOUs: true
    # CA:
    #   Country: US
    #   Province: California
    #   Locality: San Francisco
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
      
PeerOrgs:
  - Name: Bolt
    Domain: bolt.com
    EnableNodeOUs: true
    # CA:
    #   Country: US
    #   Province: California
    #   Locality: San Francisco
    Template:
      Count: 1
      SANS:
        - localhost
      Hostname: devpeer
    Users:
      Count: 2

  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    # CA:
    #   Country: US
    #   Province: California
    #   Locality: San Francisco
    Users:
      Count: 1


      

      