# The default template
# If edit this file, should edit gen-crypto.sh either

OrdererOrgs:
  - Name: Orderer
    Domain: default.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
PeerOrgs:
  - Name: Default
    Domain: default.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: default
        CommonName: devpeer
    Users:
      Count: 1


      

      