# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  fabric:

services:
  PEER_NAME:
    container_name: $PEER_NAME
    
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=$PEER_NAME
      - CORE_PEER_ADDRESS=$PEER_NAME.$DOMAIN:$PORT
      - CORE_PEER_LISTENADDRESS=0.0.0.0:$PORT
      - CORE_PEER_CHAINCODEADDRESS=$PEER_NAME.$DOMAIN:$CHAICODE_PORT
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:$CHAICODE_PORT
      - CORE_PEER_GOSSIP_BOOTSTRAP=$PEER_NAME.$DOMAIN:$PORT
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=$PEER_NAME.$DOMAIN:$PORT
      - CORE_PEER_LOCALMSPID=$ORGMSP
    volumes:
        - $MSP_PATH/msp:/etc/hyperledger/fabric/msp
        - $MSP_PATH/tls:/etc/hyperledger/fabric/tls
        - ../artefacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/artefacts
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - $PORT:7051
    networks:
      - fabric
    extra_hosts:
      - "devpeer.bolt.com:10.110.203.38"
      - "orderer0.bolt.com:10.110.203.38"

